name: Build and Commit PDF
on: [push]

jobs:
    build:
        name: Build PDF
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
        - name: Checkout master
          uses: actions/checkout@v3
          with:  
            fetch-depth: 0
        - uses: yusancky/setup-typst@v2
          id: setup-typst
          with:
            version: 'v0.7.0'
        - name: Build PDF
          run: 'make all'
        - name: Git Auto Commit
          uses: stefanzweifel/git-auto-commit-action@v5.0.0
          with:
            commit_message: 'Update resume PDF'
            commit_options: '--no-verify --signoff'
            branch: 'main'
            file_pattern: '*.pdf'
            repository: .
            